name: Deploy Published Release to GCP

on:
  release:
    types: [published]
  
jobs:
  upload-to-gcp:
    runs-on: ubuntu-22.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        
      # Removes 'v' from version string
      - name: Format Version String
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          # Strip the 'v' prefix
          STRIPPED="${TAG_NAME#v}"
          
          # Split into parts and apply zero-padding to each number
          IFS='.' read -r year month day <<< "$STRIPPED"
          PADDED_VERSION=$(printf "%02d.%02d.%02d" "$year" "$month" "$day")
          
          # Save to env
          echo "CLEAN_VERSION=$PADDED_VERSION" >> $GITHUB_ENV
          echo "Formatted version for GCP: $PADDED_VERSION"
          
      - name: Download Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p release_assets
          gh release download ${{ github.event.release.tag_name }} --dir release_assets
          # remove update files
          rm -f release_assets/*.yml 
          # remove mac specific update zip
          rm -f release_assets/*.zip

      # Google Cloud Platform Auth (Keyless WIF Handshake)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/763924193823/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'discovery-ci-deployer@secure-brook-401818.iam.gserviceaccount.com'

      # Upload contents to discovery-public/{version}/ bucket
      - name: Upload to Cloud Storage
        uses: google-github-actions/upload-cloud-storage@v3
        with:
          path: 'release_assets'
          destination: 'discovery-public/${{ env.CLEAN_VERSION }}'
          parent: false
          process_gcloudignore: false
