name: Deploy Published Release to GCP

on:
  release:
    types: [published]
  
jobs:
  upload-to-gcp:
    runs-on: ubuntu-22.04

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        
      # Removes 'v' from version string
      - name: Format Version String
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          # Strip the 'v' prefix
          STRIPPED="${TAG_NAME#v}"
          
          # Split into parts and apply zero-padding to each number
          IFS='.' read -r year month day <<< "$STRIPPED"
          PADDED_VERSION=$(printf "%02d.%02d.%02d" "$year" "$month" "$day")
          
          # Save to env
          echo "CLEAN_VERSION=$PADDED_VERSION" >> $GITHUB_ENV
          echo "Formatted version for GCP: $PADDED_VERSION"
          
      - name: Download Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p release_assets
          gh release download ${{ github.event.release.tag_name }} --dir release_assets
          # remove update files
          rm -f release_assets/*.yml 
          # remove mac specific update zip
          rm -f release_assets/*.zip

      # Google Cloud Platform Auth (Keyless WIF Handshake)
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          workload_identity_provider: 'projects/763924193823/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'discovery-ci-deployer@secure-brook-401818.iam.gserviceaccount.com'

      # Upload contents to discovery-public/{version}/ bucket and replace discovery-public/latest/
      - name: Upload to Cloud Storage
        run: |
          echo "Uploading version folder..."
          gcloud storage cp --recursive release_assets/* gs://discovery-public/${{ env.CLEAN_VERSION }}/

          echo "Renaming assets for latest..."
          mkdir -p latest_assets
          cp release_assets/* latest_assets/

          RAW_VERSION="${TAG_NAME#v}"

          cd latest_assets
          for file in *; do
            if [ -f "$file" ]; then
              # replace "{ver}-installer" with "installer-latest"
              new_name="${file//-$RAW_VERSION-installer/-installer-latest}"

              # no "installer", replace {ver} with "latest"
              new_name="${new_name//-$RAW_VERSION/-latest}"

              if [ "$file" != "$new_name" ]; then
                mv "$file" "$new_name"
                echo "Renamed: $file -> $new_name"
              fi
            fi
          done
          cd ..
          
          echo "Removing old latest/..."
          gcloud storage rm --recursive gs://discovery-public/latest/ || true

          echo "Uploading new latest/..."
          gcloud storage cp --recursive latest_assets/* gs://discovery-public/latest/
